config/routes.rb
Rails.application.routes.draw do
 # get 'applicants/:id/upload' => 'applicants#upload', as: 'upload_applicant'

  resources :applicants
  resources :challenges

  get '/applicants/logging/:id/', to: 'applicants#logging'
  get '/applicants/score/:id/', to: 'applicants#score'
  get '/challenges/result/:id/', to: 'challenges#result'
  post '/applicants/:id' => 'applicants#building', as: 'building_applicant'
  root :to => 'applicants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
  mount_uploader :attachments3, Attachments3Uploader
  has_secure_token :token
  belongs_to :challenge
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :applicants
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy, :logging, :building, :score]
  before_action :set_docker, only: [:update, :show]

  def index
    @applicants = Applicant.all
  end

  def show
    render :show
  end

  def new
    @challenges = Challenge.all
    @applicant = Applicant.new
  end

  def edit
    @challenges = Challenge.all
  end

  def logging
    render plain:@applicant.log
  end
  def score
    render plain:@applicant.score
  end

  def building
    RunJob.perform_later @applicant.id

    require 'timers'
    timers = Timers::Group.new

    paused_timer = timers.every(7) { puts "5sec paused" }

    paused_timer.resume
    10.times { timers.wait } # will fire timer

    @docker = get_docker @applicant.id

    @docker.delete(force: true)

    begin

    rescue
      puts "applicant_#{@applicant.id} docker stop failed"
    end

    render :show
  end

  def get_docker(id)
    begin
      return Docker::Container.get("applicant_#{id}_run")
    rescue
      return nil
    end
  end

  def create
    @challenges = Challenge.all

    @applicant = Applicant.new(applicant_params)
    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html {redirect_to @applicant.challenge, notice: 'Applicant was successfully updated'}
        if @applicant.attachment != nil
          #puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
          output = system("rm -f -r #{__dir__}/../../unzip/#{@applicant.id}/")
          output = system("unzip -o ./public/#{@applicant.attachment} -d ./unzip/#{@applicant.id} ")
          puts  "unzip : #{output}"


          #output = system("sudo rm -r ./unzip/#{@applicant.id}/src/test")
          #output = system("sudo cp -r ./tmp/test ./unzip/#{@applicant.id}/src")
          #output = system("sudo rm -f ./public/#{@applicant.attachment}")
          #puts "rm : #{output}"
          #output = system("cd ./unzip/#{@applicant.id} && zip -r ../../public#{@applicant.attachment} ./*")
          #puts "zip : #{output}"
          # upload S3
          #@applicant.attachments3 = @applicant.attachment
        end
      else
        format.html {render :edit}
      end
    end
    @applicant.update(applicant_params)
  end

  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html {redirect_to applicants_url, notice: 'Applicant was successfully destroyed. ' }
    end
  end

  def page

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_applicant
    @applicant = Applicant.find(params[:id])
  end

  def set_docker
    begin
      @docker = Docker::Container.get("applicant_#{@applicant.id}")
    rescue
      @docker = nil
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def applicant_params
    params.require(:applicant).permit(:name, :email, :score, :token, :challenge_id, :attachment, :id, :log, :language)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ChallengesHelper
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :destroy, :update, :edit, :result]
  before_action :set_applicant, only: [:show, :update, :result]

  def index
    @challenges = Challenge.all
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(challenge_params)
    if @challenge.save
      redirect_to challenges_path
    else
      render 'new'
    end
  end

  def destroy
    @challenge.destroy
    redirect_to challenges_path
  end
  def result
  end
  def show
  end

  def update
    respond_to do |format|
      format.json {render plain: @applicant.log}
      TestJob.perform_later @applicant.id
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_challenge
    @challenge = Challenge.find(params[:id])
  end

  def set_applicant
    @applicant = Applicant.where(challenge_id: params[:id]).find_by(token: params[:token])
    if @applicant
      log_in @applicant
    else
      @applicant = Applicant.where(challenge_id: params[:id]).find_by(token: session[:token])
      render json: {error: 'Not Authorized'}, status: 401 unless @applicant
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def challenge_params
    params.require(:challenge).permit(:title, :description)
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
  def log_in(applicant)
    session[:token] = applicant.token
  end

  def current_user
    @current_user ||= Applicant.find_by(token: session[:token])
  end

  def user_signed_in?
    !current_user.nil?
  end
end

app/views/applicants/_form.html.erb
<%= form_for(@applicant) do |a| %>
    <% if @applicant.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@applicant.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @applicant.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class = "field">
      <%= a.label :name %>
      <%= a.text_field :name, style: 'width:345px; height:25px;' %>
    </div>
    <div class = "field">
      <%= a.label :email %>
      <%= a.text_field :email, style: 'width:350px; height:25px;'%>
    </div>
    <br>
    <div class = "action">
      <%= a.label :challenge %>
      <%= a.select(:challenge_id, @challenges.collect { |r| [r.id]}) %> &nbsp;
      <%= a.submit %>
    </div>
    <br>
<% end %>

app/views/applicants/edit.html.erb
<head>
  <div class="title">
    <img class="titleImg" src="<%=image_path('codeacademyW.png')%>" />
    <div class="titleText">Editing Post</div>
  </div>
</head>


<br>
<div class="edition">
  <%= render 'form' %>

  <%= link_to 'Show', @applicant %> |
  <%= link_to 'Back', applicants_path %>
</div>

app/views/applicants/index.html.erb
<head>
  <div class="title">
    <img class="titleImg" src="<%=image_path('codeacademyW.png')%>" />
    <div class="titleText">Listing Appicants</div>
  </div>
</head>
<table style="text-align: center" width="100%" rules=none>
  <thead>
  <tr style="color:white" bgcolor="black" height="35">
    <th>Name</th>
    <th>Email</th>
    <th>Challenge</th>
    <th colspan = "2">Function</th>
    <th><%= link_to 'New Applicant', new_applicant_path %></th>
  </tr>
  </thead>

  <tbody>
  <% @applicants.each do |applicant| %>
      <tr height="30" bgcolor="silver">
        <td><%= applicant.name %></td>
        <td><%= applicant.email %></td>
        <td><%= applicant.challenge.title %></td>
        <td><%= link_to 'Show', applicant %></td>
        <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
        <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<br>
<div class="bottom" >
  <img class="invition" src="<%=image_path('invite.jpg')%>" />
</div>

app/views/applicants/new.html.erb
<head>
  <div class="title">
    <img class="titleImg" src="<%=image_path('codeacademyW.png')%>" />
    <div class="titleText">New Appicants</div>
  </div>
</head>


<br>
<div class="edition">
  <%= render 'form', applicant: @applicant %>

  <%= link_to 'Back', applicants_path %>
</div>

app/views/applicants/show.html.erb
<head>
  <div class="title">
    <img class="titleImg" src="<%=image_path('codeacademyW.png')%>" />
    <div class="titleText">Show Appicants</div>
  </div>
</head>

<div>
  <img class="sideImg" src="<%=image_path('showimg.jpeg')%>" />
</div>
<div class="show">
  <div>
    <strong>Name:</strong>
    <%= @applicant.name %>
  </div>

  <div>
    <strong>Email:</strong>
    <%= @applicant.email %>
  </div>

  <div>
    <strong>Challenge:</strong>
    <%= @applicant.challenge.title %>
  </div>

  <div>
    <table>
      <thead>
        <th>Web_Build :</th>
        <td><%= button_to 'Build', building_applicant_path, data: { confirm: '50초 동안 확인할 수 있습니다.'}  %></td>
      </thead>
    </table>
    <strong>View_Site:</strong>
    <% id = ((@applicant.id).to_s) %>
    <% host_ip = Socket.ip_address_list.detect{|intf| intf.ipv4_private?}.ip_address %>
    <% port = (6000 + @applicant.id).to_s %>
    <%= link_to 'Link', 'http://' + host_ip + ':' + port, :target => '_blank'%>
  </div>
  <div class="edition">
    <%= link_to 'Edit', edit_applicant_path(@applicant) %> |
    <%= link_to 'Back', applicants_path %>
  </div>
</div>

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
    <% if @challenge.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @challenge.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<h1>Challenges#index</h1>

</br>

<table>

  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.title %></td>
        <td><%= challenge.description %></td>
        <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<h1>New Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/result.html.erb
<%= hidden_field_tag :current_id, "#{@applicant.id}"%>

<head>
  <div class="headerChallenge">
    <img class="headerImg" src="<%=image_path('unity&web.png')%>" />
    <div class="headerText">Spring_WebTest</div>
    <div class="userChallenge">
      "<%= @applicant.name %>"님 시험이 종료되었습니다!
    </div>
  </div>
</head>
<br>
<br>
<div class="resultChallenge">
  <img class="resultImg" src="<%=image_path('resultImg')%>" />
  <div class="resultBox">
    <b>최종점수</b>
    <div class="scorePoint"></div>
  </div>
</div>

app/views/challenges/show.html.erb
<%= hidden_field_tag :current_id, "#{@applicant.id}"%>

<head>
  <div class="headerChallenge">
    <img class="headerImg" src="<%=image_path('unity&web.png')%>" />
    <div class="headerText">Spring_WebTest</div>
    <div class="userChallenge">
      "<%= @applicant.name %>"님 환영합니다!
    </div>
  </div>
</head>
<br>
<br>
<div class="showChallenge">
  <div class="goal">
    <strong>Goal : </strong>
    <%= @challenge.title %> - <%= @challenge.goal %>
  </div>
  <br><br>
  <hr>
  <br><br>

  <div class="infoBox">
    Information
    <textarea  style="width: 680px; height:400px;" readonly="readonly" ><%= @challenge.information %></textarea>
  </div>
  <div class="infoBox2">
    Ex
    <div><%= image_tag "#{@challenge.id}.jpg", height: '320', width: '410' %></div>
  </div>


  <div class="infoBox">
    Description
    <textarea style="width: 680px; height:75px;" readonly="readonly"><%= @challenge.description %></textarea>
  </div>

  <div class="itemChallenge">
    <div>
      <%=form_for @applicant do |f|%>
      <strong>Language - </strong>
      <%= f.select :language, [['SpringBoot'],['RubyonRails']] %>
          <%=f.submit "Change"%>
      <%end%>
    </div>
    <div>
    <strong>File_Download : </strong>
    <%= link_to 'link', "/download/#{@challenge.id}/#{@challenge.title}/#{@applicant.language}.zip" %>
    <!--(, download: 'data.zip')-->
    </div>

    <div>
    <%= form_for @applicant do |f| %>
        <strong>Upload_File : </strong>
        <%= f.file_field :attachment, accept: '.zip'  %>
        <%= f.submit "Upload" %>
    <% end %>
    </div>

    <%= form_for(@challenge, remote: true) do |g| %>
        <strong>Submit : </strong>
        <%= g.submit "GradeTest", class: "gradeTest" %>
    <%end%>
    </div>
  </div>
</div>
<div class="bottomChallenge">
  <div class="resultBox">
    <div class="resultBold">실행상태</div>
    <div class="resultPoint"></div>
    <div class="result">Ready</div>
  </div>
  <br>
  <div class="finChallenge">
    <%= link_to '시험종료', '/challenges/result/'+"#{@applicant.id}", data: { confirm: 'Are you sure?' }%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>